import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mastermind.settings")
django.setup()

from app_game.models import Frage, Antwort

def daten_einfuegen():
    frage1 = Frage.objects.create(text='What is the capital of Germany?')
    Antwort.objects.create(frage=frage1, text='Berlin', ist_korrekt=True)
    Antwort.objects.create(frage=frage1, text='Rome', ist_korrekt=False)
    Antwort.objects.create(frage=frage1, text='London', ist_korrekt=False)
    Antwort.objects.create(frage=frage1, text='Paris', ist_korrekt=False)

    frage2 = Frage.objects.create(text='How many states does Germany have?')
    Antwort.objects.create(frage=frage2, text='10', ist_korrekt=False)
    Antwort.objects.create(frage=frage2, text='16', ist_korrekt=True)
    Antwort.objects.create(frage=frage2, text='20', ist_korrekt=False)
    Antwort.objects.create(frage=frage2, text='25', ist_korrekt=False)

    frage3 = Frage.objects.create(text='Which river flows through Berlin?')
    Antwort.objects.create(frage=frage3, text='Rhine', ist_korrekt=False)
    Antwort.objects.create(frage=frage3, text='Danube', ist_korrekt=False)
    Antwort.objects.create(frage=frage3, text='Elbe', ist_korrekt=False)
    Antwort.objects.create(frage=frage3, text='Spree', ist_korrekt=True)

    frage4 = Frage.objects.create(text='When was the Berlin Wall built?')
    Antwort.objects.create(frage=frage4, text='1945', ist_korrekt=False)
    Antwort.objects.create(frage=frage4, text='1952', ist_korrekt=False)
    Antwort.objects.create(frage=frage4, text='1961', ist_korrekt=True)
    Antwort.objects.create(frage=frage4, text='1970', ist_korrekt=False)

    frage5 = Frage.objects.create(text='Which German city is also known as the "Free and Hanseatic City"?')
    Antwort.objects.create(frage=frage5, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage5, text='Frankfurt', ist_korrekt=False)
    Antwort.objects.create(frage=frage5, text='Hamburg', ist_korrekt=True)
    Antwort.objects.create(frage=frage5, text='Cologne', ist_korrekt=False)

    frage6 = Frage.objects.create(text='Which German automobile company produces the brand "Volkswagen"?')
    Antwort.objects.create(frage=frage6, text='BMW', ist_korrekt=False)
    Antwort.objects.create(frage=frage6, text='Mercedes-Benz', ist_korrekt=False)
    Antwort.objects.create(frage=frage6, text='Audi', ist_korrekt=False)
    Antwort.objects.create(frage=frage6, text='Volkswagen', ist_korrekt=True)

    frage7 = Frage.objects.create(text='Who is the current Chancellor of Germany?')
    Antwort.objects.create(frage=frage7, text='Angela Merkel', ist_korrekt=False)
    Antwort.objects.create(frage=frage7, text='Olaf Scholz', ist_korrekt=True)
    Antwort.objects.create(frage=frage7, text='Annalena Baerbock', ist_korrekt=False)
    Antwort.objects.create(frage=frage7, text='Armin Laschet', ist_korrekt=False)

    frage8 = Frage.objects.create(text='What is the highest mountain in Germany?')
    Antwort.objects.create(frage=frage8, text='Zugspitze', ist_korrekt=True)
    Antwort.objects.create(frage=frage8, text='Watzmann', ist_korrekt=False)
    Antwort.objects.create(frage=frage8, text='Feldberg', ist_korrekt=False)
    Antwort.objects.create(frage=frage8, text='Brocken', ist_korrekt=False)

    frage9 = Frage.objects.create(text='Which German composer is known for his famous symphonies?')
    Antwort.objects.create(frage=frage9, text='Ludwig van Beethoven', ist_korrekt=True)
    Antwort.objects.create(frage=frage9, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage9, text='Wolfgang Amadeus Mozart', ist_korrekt=False)
    Antwort.objects.create(frage=frage9, text='Richard Wagner', ist_korrekt=False)

    frage10 = Frage.objects.create(text='Which German scientist developed the theory of relativity?')
    Antwort.objects.create(frage=frage10, text='Isaac Newton', ist_korrekt=False)
    Antwort.objects.create(frage=frage10, text='Albert Einstein', ist_korrekt=True)
    Antwort.objects.create(frage=frage10, text='Niels Bohr', ist_korrekt=False)
    Antwort.objects.create(frage=frage10, text='Marie Curie', ist_korrekt=False)

    frage11 = Frage.objects.create(text='Which German city is famous for its Oktoberfest celebration?')
    Antwort.objects.create(frage=frage11, text='Munich', ist_korrekt=True)
    Antwort.objects.create(frage=frage11, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage11, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage11, text='Hamburg', ist_korrekt=False)

    frage12 = Frage.objects.create(text='Who was the first Chancellor of Germany?')
    Antwort.objects.create(frage=frage12, text='Konrad Adenauer', ist_korrekt=True)
    Antwort.objects.create(frage=frage12, text='Helmut Kohl', ist_korrekt=False)
    Antwort.objects.create(frage=frage12, text='Angela Merkel', ist_korrekt=False)
    Antwort.objects.create(frage=frage12, text='Gerhard Schröder', ist_korrekt=False)

    frage13 = Frage.objects.create(text='Which German city is famous for its Brandenburg Gate?')
    Antwort.objects.create(frage=frage13, text='Berlin', ist_korrekt=True)
    Antwort.objects.create(frage=frage13, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage13, text='Hamburg', ist_korrekt=False)
    Antwort.objects.create(frage=frage13, text='Cologne', ist_korrekt=False)

    frage14 = Frage.objects.create(text='Which German composer is known for his famous "Ode to Joy"?')
    Antwort.objects.create(frage=frage14, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage14, text='Wolfgang Amadeus Mozart', ist_korrekt=False)
    Antwort.objects.create(frage=frage14, text='Ludwig van Beethoven', ist_korrekt=True)
    Antwort.objects.create(frage=frage14, text='Richard Wagner', ist_korrekt=False)

    frage15 = Frage.objects.create(text='Which German city is known for its Documenta exhibition of contemporary art?')
    Antwort.objects.create(frage=frage15, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage15, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage15, text='Dresden', ist_korrekt=False)
    Antwort.objects.create(frage=frage15, text='Kassel', ist_korrekt=True)

    frage16 = Frage.objects.create(text='Which German scientist discovered the X-rays?')
    Antwort.objects.create(frage=frage16, text='Max Planck', ist_korrekt=False)
    Antwort.objects.create(frage=frage16, text='Wilhelm Conrad Roentgen', ist_korrekt=True)
    Antwort.objects.create(frage=frage16, text='Albert Einstein', ist_korrekt=False)
    Antwort.objects.create(frage=frage16, text='Werner Heisenberg', ist_korrekt=False)

    frage17 = Frage.objects.create(text='Which German city is famous for its Mercedes-Benz and Porsche car factories?')
    Antwort.objects.create(frage=frage17, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage17, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage17, text='Stuttgart', ist_korrekt=True)
    Antwort.objects.create(frage=frage17, text='Cologne', ist_korrekt=False)

    frage18 = Frage.objects.create(text='Who wrote the famous German novel "Faust"?')
    Antwort.objects.create(frage=frage18, text='Johann Wolfgang von Goethe', ist_korrekt=True)
    Antwort.objects.create(frage=frage18, text='Thomas Mann', ist_korrekt=False)
    Antwort.objects.create(frage=frage18, text='Franz Kafka', ist_korrekt=False)
    Antwort.objects.create(frage=frage18, text='Heinrich Heine', ist_korrekt=False)

    frage19 = Frage.objects.create(text='Which German city is famous for its university and historic old town?')
    Antwort.objects.create(frage=frage19, text='Leipzig', ist_korrekt=False)
    Antwort.objects.create(frage=frage19, text='Heidelberg', ist_korrekt=True)
    Antwort.objects.create(frage=frage19, text='Hamburg', ist_korrekt=False)
    Antwort.objects.create(frage=frage19, text='Cologne', ist_korrekt=False)

    frage20 = Frage.objects.create(text='Which German scientist is known for his theory of general relativity?')
    Antwort.objects.create(frage=frage20, text='Isaac Newton', ist_korrekt=False)
    Antwort.objects.create(frage=frage20, text='Albert Einstein', ist_korrekt=True)
    Antwort.objects.create(frage=frage20, text='Niels Bohr', ist_korrekt=False)
    Antwort.objects.create(frage=frage20, text='Marie Curie', ist_korrekt=False)

    frage21 = Frage.objects.create(text='Which German city is famous for its annual Carnival celebration?')
    Antwort.objects.create(frage=frage21, text='Cologne', ist_korrekt=True)
    Antwort.objects.create(frage=frage21, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage21, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage21, text='Hamburg', ist_korrekt=False)

    frage22 = Frage.objects.create(text='Who is the current Chancellor of Germany as of 2023?')
    Antwort.objects.create(frage=frage22, text='Angela Merkel', ist_korrekt=False)
    Antwort.objects.create(frage=frage22, text='Olaf Scholz', ist_korrekt=True)
    Antwort.objects.create(frage=frage22, text='Annalena Baerbock', ist_korrekt=False)
    Antwort.objects.create(frage=frage22, text='Armin Laschet', ist_korrekt=False)

    frage23 = Frage.objects.create(text='Which German city is famous for its Gothic cathedral?')
    Antwort.objects.create(frage=frage23, text='Frankfurt', ist_korrekt=False)
    Antwort.objects.create(frage=frage23, text='Dresden', ist_korrekt=False)
    Antwort.objects.create(frage=frage23, text='Cologne', ist_korrekt=True)
    Antwort.objects.create(frage=frage23, text='Hamburg', ist_korrekt=False)

    frage24 = Frage.objects.create(text='Which German composer is known for his famous "The Four Seasons" composition?')
    Antwort.objects.create(frage=frage24, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage24, text='Antonio Vivaldi', ist_korrekt=True)
    Antwort.objects.create(frage=frage24, text='Ludwig van Beethoven', ist_korrekt=False)
    Antwort.objects.create(frage=frage24, text='Richard Wagner', ist_korrekt=False)

    frage25 = Frage.objects.create(text='Which German city is known for its Volkswagen car factory?')
    Antwort.objects.create(frage=frage25, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage25, text='Stuttgart', ist_korrekt=False)
    Antwort.objects.create(frage=frage25, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage25, text='Wolfsburg', ist_korrekt=True)

    frage26 = Frage.objects.create(text='Who was the first German astronaut to travel to space?')
    Antwort.objects.create(frage=frage26, text='Alexander Gerst', ist_korrekt=False)
    Antwort.objects.create(frage=frage26, text='Klaus-Dietrich Flade', ist_korrekt=False)
    Antwort.objects.create(frage=frage26, text='Reinhard Furrer', ist_korrekt=False)
    Antwort.objects.create(frage=frage26, text='Sigmund Jähn', ist_korrekt=True)

    frage27 = Frage.objects.create(text='Which German city is known for its Alte Pinakothek art museum?')
    Antwort.objects.create(frage=frage27, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage27, text='Dresden', ist_korrekt=False)
    Antwort.objects.create(frage=frage27, text='Munich', ist_korrekt=True)
    Antwort.objects.create(frage=frage27, text='Cologne', ist_korrekt=False)

    frage28 = Frage.objects.create(text='Who is the famous German philosopher known for his work on existentialism?')
    Antwort.objects.create(frage=frage28, text='Immanuel Kant', ist_korrekt=False)
    Antwort.objects.create(frage=frage28, text='Friedrich Nietzsche', ist_korrekt=True)
    Antwort.objects.create(frage=frage28, text='Martin Heidegger', ist_korrekt=False)
    Antwort.objects.create(frage=frage28, text='Arthur Schopenhauer', ist_korrekt=False)

    frage29 = Frage.objects.create(text='Which German city is famous for its Frauenkirche (Church of Our Lady)?')
    Antwort.objects.create(frage=frage29, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage29, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage29, text='Dresden', ist_korrekt=True)
    Antwort.objects.create(frage=frage29, text='Hamburg', ist_korrekt=False)

    frage30 = Frage.objects.create(text='Which German scientist is known as the father of modern physics?')
    Antwort.objects.create(frage=frage30, text='Isaac Newton', ist_korrekt=False)
    Antwort.objects.create(frage=frage30, text='Albert Einstein', ist_korrekt=True)
    Antwort.objects.create(frage=frage30, text='Niels Bohr', ist_korrekt=False)
    Antwort.objects.create(frage=frage30, text='Marie Curie', ist_korrekt=False)

    frage31 = Frage.objects.create(text='Which German city is famous for its Semperoper (Semper Opera House)?')
    Antwort.objects.create(frage=frage31, text='Frankfurt', ist_korrekt=False)
    Antwort.objects.create(frage=frage31, text='Dresden', ist_korrekt=True)
    Antwort.objects.create(frage=frage31, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage31, text='Hamburg', ist_korrekt=False)

    frage32 = Frage.objects.create(text='Who is the German author of the famous novel "The Neverending Story"?')
    Antwort.objects.create(frage=frage32, text='Hermann Hesse', ist_korrekt=False)
    Antwort.objects.create(frage=frage32, text='Franz Kafka', ist_korrekt=False)
    Antwort.objects.create(frage=frage32, text='Günter Grass', ist_korrekt=False)
    Antwort.objects.create(frage=frage32, text='Michael Ende', ist_korrekt=True)

    frage33 = Frage.objects.create(text='Which German city is famous for its Neuschwanstein Castle?')
    Antwort.objects.create(frage=frage33, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage33, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage33, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage33, text='Füssen', ist_korrekt=True)

    frage34 = Frage.objects.create(text='Who composed the famous German opera "The Magic Flute"?')
    Antwort.objects.create(frage=frage34, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage34, text='Wolfgang Amadeus Mozart', ist_korrekt=True)
    Antwort.objects.create(frage=frage34, text='Ludwig van Beethoven', ist_korrekt=False)
    Antwort.objects.create(frage=frage34, text='Richard Wagner', ist_korrekt=False)

    frage35 = Frage.objects.create(text='Which German city is known for its Zeppelin Museum?')
    Antwort.objects.create(frage=frage35, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage35, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage35, text='Friedrichshafen', ist_korrekt=True)
    Antwort.objects.create(frage=frage35, text='Cologne', ist_korrekt=False)

    frage36 = Frage.objects.create(text='Who is the German tennis player who has won the most Grand Slam titles?')
    Antwort.objects.create(frage=frage36, text='Boris Becker', ist_korrekt=False)
    Antwort.objects.create(frage=frage36, text='Steffi Graf', ist_korrekt=True)
    Antwort.objects.create(frage=frage36, text='Angelique Kerber', ist_korrekt=False)
    Antwort.objects.create(frage=frage36, text='Alexander Zverev', ist_korrekt=False)

    frage37 = Frage.objects.create(text='Which German city is famous for its Romantic Road, a scenic tourist route?')
    Antwort.objects.create(frage=frage37, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage37, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage37, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage37, text='Rothenburg ob der Tauber', ist_korrekt=True)

    frage38 = Frage.objects.create(text='Who is the German philosopher known for his work on Marxism?')
    Antwort.objects.create(frage=frage38, text='Immanuel Kant', ist_korrekt=False)
    Antwort.objects.create(frage=frage38, text='Friedrich Nietzsche', ist_korrekt=False)
    Antwort.objects.create(frage=frage38, text='Karl Marx', ist_korrekt=True)
    Antwort.objects.create(frage=frage38, text='Arthur Schopenhauer', ist_korrekt=False)

    frage39 = Frage.objects.create(text='Which German city is famous for its St. Nicholas Church?')
    Antwort.objects.create(frage=frage39, text='Frankfurt', ist_korrekt=False)
    Antwort.objects.create(frage=frage39, text='Dresden', ist_korrekt=False)
    Antwort.objects.create(frage=frage39, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage39, text='Leipzig', ist_korrekt=True)

    frage40 = Frage.objects.create(text='Who is the German filmmaker known for his movies "Metropolis" and "M"?')
    Antwort.objects.create(frage=frage40, text='Fritz Lang', ist_korrekt=True)
    Antwort.objects.create(frage=frage40, text='Werner Herzog', ist_korrekt=False)
    Antwort.objects.create(frage=frage40, text='Rainer Werner Fassbinder', ist_korrekt=False)
    Antwort.objects.create(frage=frage40, text='Wim Wenders', ist_korrekt=False)
    
    print("Daten erfolgreich eingefügt.")

if __name__ == '__main__':
    daten_einfuegen()