import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mastermind.settings")
django.setup()

from app_game.models import Frage, Antwort

def daten_einfuegen():
    frage1 = Frage.objects.create(text='What is the capital of Germany?')
    Antwort.objects.create(frage=frage1, text='Berlin', ist_korrekt=True)
    Antwort.objects.create(frage=frage1, text='Rome', ist_korrekt=False)
    Antwort.objects.create(frage=frage1, text='London', ist_korrekt=False)
    Antwort.objects.create(frage=frage1, text='Paris', ist_korrekt=False)

    frage2 = Frage.objects.create(text='How many states does Germany have?')
    Antwort.objects.create(frage=frage2, text='10', ist_korrekt=False)
    Antwort.objects.create(frage=frage2, text='16', ist_korrekt=True)
    Antwort.objects.create(frage=frage2, text='20', ist_korrekt=False)
    Antwort.objects.create(frage=frage2, text='25', ist_korrekt=False)

    frage3 = Frage.objects.create(text='Which river flows through Berlin?')
    Antwort.objects.create(frage=frage3, text='Rhine', ist_korrekt=False)
    Antwort.objects.create(frage=frage3, text='Danube', ist_korrekt=False)
    Antwort.objects.create(frage=frage3, text='Elbe', ist_korrekt=False)
    Antwort.objects.create(frage=frage3, text='Spree', ist_korrekt=True)

    frage4 = Frage.objects.create(text='When was the Berlin Wall built?')
    Antwort.objects.create(frage=frage4, text='1945', ist_korrekt=False)
    Antwort.objects.create(frage=frage4, text='1952', ist_korrekt=False)
    Antwort.objects.create(frage=frage4, text='1961', ist_korrekt=True)
    Antwort.objects.create(frage=frage4, text='1970', ist_korrekt=False)

    frage5 = Frage.objects.create(text='Which German city is also known as the "Free and Hanseatic City"?')
    Antwort.objects.create(frage=frage5, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage5, text='Frankfurt', ist_korrekt=False)
    Antwort.objects.create(frage=frage5, text='Hamburg', ist_korrekt=True)
    Antwort.objects.create(frage=frage5, text='Cologne', ist_korrekt=False)

    frage6 = Frage.objects.create(text='Which German automobile company produces the brand "Volkswagen"?')
    Antwort.objects.create(frage=frage6, text='BMW', ist_korrekt=False)
    Antwort.objects.create(frage=frage6, text='Mercedes-Benz', ist_korrekt=False)
    Antwort.objects.create(frage=frage6, text='Audi', ist_korrekt=False)
    Antwort.objects.create(frage=frage6, text='Volkswagen', ist_korrekt=True)

    frage7 = Frage.objects.create(text='Who is the current Chancellor of Germany?')
    Antwort.objects.create(frage=frage7, text='Angela Merkel', ist_korrekt=False)
    Antwort.objects.create(frage=frage7, text='Olaf Scholz', ist_korrekt=True)
    Antwort.objects.create(frage=frage7, text='Annalena Baerbock', ist_korrekt=False)
    Antwort.objects.create(frage=frage7, text='Armin Laschet', ist_korrekt=False)

    frage8 = Frage.objects.create(text='What is the highest mountain in Germany?')
    Antwort.objects.create(frage=frage8, text='Zugspitze', ist_korrekt=True)
    Antwort.objects.create(frage=frage8, text='Watzmann', ist_korrekt=False)
    Antwort.objects.create(frage=frage8, text='Feldberg', ist_korrekt=False)
    Antwort.objects.create(frage=frage8, text='Brocken', ist_korrekt=False)

    frage9 = Frage.objects.create(text='Which German composer is known for his famous symphonies?')
    Antwort.objects.create(frage=frage9, text='Ludwig van Beethoven', ist_korrekt=True)
    Antwort.objects.create(frage=frage9, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage9, text='Wolfgang Amadeus Mozart', ist_korrekt=False)
    Antwort.objects.create(frage=frage9, text='Richard Wagner', ist_korrekt=False)

    frage10 = Frage.objects.create(text='Which German scientist developed the theory of relativity?')
    Antwort.objects.create(frage=frage10, text='Isaac Newton', ist_korrekt=False)
    Antwort.objects.create(frage=frage10, text='Albert Einstein', ist_korrekt=True)
    Antwort.objects.create(frage=frage10, text='Niels Bohr', ist_korrekt=False)
    Antwort.objects.create(frage=frage10, text='Marie Curie', ist_korrekt=False)

    frage11 = Frage.objects.create(text='Which German city is famous for its Oktoberfest celebration?')
    Antwort.objects.create(frage=frage11, text='Munich', ist_korrekt=True)
    Antwort.objects.create(frage=frage11, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage11, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage11, text='Hamburg', ist_korrekt=False)

    frage12 = Frage.objects.create(text='Who was the first Chancellor of Germany?')
    Antwort.objects.create(frage=frage12, text='Konrad Adenauer', ist_korrekt=True)
    Antwort.objects.create(frage=frage12, text='Helmut Kohl', ist_korrekt=False)
    Antwort.objects.create(frage=frage12, text='Angela Merkel', ist_korrekt=False)
    Antwort.objects.create(frage=frage12, text='Gerhard Schröder', ist_korrekt=False)

    frage13 = Frage.objects.create(text='Which German city is famous for its Brandenburg Gate?')
    Antwort.objects.create(frage=frage13, text='Berlin', ist_korrekt=True)
    Antwort.objects.create(frage=frage13, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage13, text='Hamburg', ist_korrekt=False)
    Antwort.objects.create(frage=frage13, text='Cologne', ist_korrekt=False)

    frage14 = Frage.objects.create(text='Which German composer is known for his famous "Ode to Joy"?')
    Antwort.objects.create(frage=frage14, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage14, text='Wolfgang Amadeus Mozart', ist_korrekt=False)
    Antwort.objects.create(frage=frage14, text='Ludwig van Beethoven', ist_korrekt=True)
    Antwort.objects.create(frage=frage14, text='Richard Wagner', ist_korrekt=False)

    frage15 = Frage.objects.create(text='Which German city is known for its Documenta exhibition of contemporary art?')
    Antwort.objects.create(frage=frage15, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage15, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage15, text='Dresden', ist_korrekt=False)
    Antwort.objects.create(frage=frage15, text='Kassel', ist_korrekt=True)

    frage16 = Frage.objects.create(text='Which German scientist discovered the X-rays?')
    Antwort.objects.create(frage=frage16, text='Max Planck', ist_korrekt=False)
    Antwort.objects.create(frage=frage16, text='Wilhelm Conrad Roentgen', ist_korrekt=True)
    Antwort.objects.create(frage=frage16, text='Albert Einstein', ist_korrekt=False)
    Antwort.objects.create(frage=frage16, text='Werner Heisenberg', ist_korrekt=False)

    frage17 = Frage.objects.create(text='Which German city is famous for its Mercedes-Benz and Porsche car factories?')
    Antwort.objects.create(frage=frage17, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage17, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage17, text='Stuttgart', ist_korrekt=True)
    Antwort.objects.create(frage=frage17, text='Cologne', ist_korrekt=False)

    frage18 = Frage.objects.create(text='Who wrote the famous German novel "Faust"?')
    Antwort.objects.create(frage=frage18, text='Johann Wolfgang von Goethe', ist_korrekt=True)
    Antwort.objects.create(frage=frage18, text='Thomas Mann', ist_korrekt=False)
    Antwort.objects.create(frage=frage18, text='Franz Kafka', ist_korrekt=False)
    Antwort.objects.create(frage=frage18, text='Heinrich Heine', ist_korrekt=False)

    frage19 = Frage.objects.create(text='Which German city is famous for its university and historic old town?')
    Antwort.objects.create(frage=frage19, text='Leipzig', ist_korrekt=False)
    Antwort.objects.create(frage=frage19, text='Heidelberg', ist_korrekt=True)
    Antwort.objects.create(frage=frage19, text='Hamburg', ist_korrekt=False)
    Antwort.objects.create(frage=frage19, text='Cologne', ist_korrekt=False)

    frage20 = Frage.objects.create(text='Which German scientist is known for his theory of general relativity?')
    Antwort.objects.create(frage=frage20, text='Isaac Newton', ist_korrekt=False)
    Antwort.objects.create(frage=frage20, text='Albert Einstein', ist_korrekt=True)
    Antwort.objects.create(frage=frage20, text='Niels Bohr', ist_korrekt=False)
    Antwort.objects.create(frage=frage20, text='Marie Curie', ist_korrekt=False)

    frage21 = Frage.objects.create(text='Which German city is famous for its annual Carnival celebration?')
    Antwort.objects.create(frage=frage21, text='Cologne', ist_korrekt=True)
    Antwort.objects.create(frage=frage21, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage21, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage21, text='Hamburg', ist_korrekt=False)

    frage22 = Frage.objects.create(text='Who is the current Chancellor of Germany as of 2023?')
    Antwort.objects.create(frage=frage22, text='Angela Merkel', ist_korrekt=False)
    Antwort.objects.create(frage=frage22, text='Olaf Scholz', ist_korrekt=True)
    Antwort.objects.create(frage=frage22, text='Annalena Baerbock', ist_korrekt=False)
    Antwort.objects.create(frage=frage22, text='Armin Laschet', ist_korrekt=False)

    frage23 = Frage.objects.create(text='Which German city is famous for its Gothic cathedral?')
    Antwort.objects.create(frage=frage23, text='Frankfurt', ist_korrekt=False)
    Antwort.objects.create(frage=frage23, text='Dresden', ist_korrekt=False)
    Antwort.objects.create(frage=frage23, text='Cologne', ist_korrekt=True)
    Antwort.objects.create(frage=frage23, text='Hamburg', ist_korrekt=False)

    frage24 = Frage.objects.create(text='Which German composer is known for his famous "The Four Seasons" composition?')
    Antwort.objects.create(frage=frage24, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage24, text='Antonio Vivaldi', ist_korrekt=True)
    Antwort.objects.create(frage=frage24, text='Ludwig van Beethoven', ist_korrekt=False)
    Antwort.objects.create(frage=frage24, text='Richard Wagner', ist_korrekt=False)

    frage25 = Frage.objects.create(text='Which German city is known for its Volkswagen car factory?')
    Antwort.objects.create(frage=frage25, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage25, text='Stuttgart', ist_korrekt=False)
    Antwort.objects.create(frage=frage25, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage25, text='Wolfsburg', ist_korrekt=True)

    frage26 = Frage.objects.create(text='Who was the first German astronaut to travel to space?')
    Antwort.objects.create(frage=frage26, text='Alexander Gerst', ist_korrekt=False)
    Antwort.objects.create(frage=frage26, text='Klaus-Dietrich Flade', ist_korrekt=False)
    Antwort.objects.create(frage=frage26, text='Reinhard Furrer', ist_korrekt=False)
    Antwort.objects.create(frage=frage26, text='Sigmund Jähn', ist_korrekt=True)

    frage27 = Frage.objects.create(text='Which German city is known for its Alte Pinakothek art museum?')
    Antwort.objects.create(frage=frage27, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage27, text='Dresden', ist_korrekt=False)
    Antwort.objects.create(frage=frage27, text='Munich', ist_korrekt=True)
    Antwort.objects.create(frage=frage27, text='Cologne', ist_korrekt=False)

    frage28 = Frage.objects.create(text='Who is the famous German philosopher known for his work on existentialism?')
    Antwort.objects.create(frage=frage28, text='Immanuel Kant', ist_korrekt=False)
    Antwort.objects.create(frage=frage28, text='Friedrich Nietzsche', ist_korrekt=True)
    Antwort.objects.create(frage=frage28, text='Martin Heidegger', ist_korrekt=False)
    Antwort.objects.create(frage=frage28, text='Arthur Schopenhauer', ist_korrekt=False)

    frage29 = Frage.objects.create(text='Which German city is famous for its Frauenkirche (Church of Our Lady)?')
    Antwort.objects.create(frage=frage29, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage29, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage29, text='Dresden', ist_korrekt=True)
    Antwort.objects.create(frage=frage29, text='Hamburg', ist_korrekt=False)

    frage30 = Frage.objects.create(text='Which German scientist is known as the father of modern physics?')
    Antwort.objects.create(frage=frage30, text='Isaac Newton', ist_korrekt=False)
    Antwort.objects.create(frage=frage30, text='Albert Einstein', ist_korrekt=True)
    Antwort.objects.create(frage=frage30, text='Niels Bohr', ist_korrekt=False)
    Antwort.objects.create(frage=frage30, text='Marie Curie', ist_korrekt=False)

    frage31 = Frage.objects.create(text='Which German city is famous for its Semperoper (Semper Opera House)?')
    Antwort.objects.create(frage=frage31, text='Frankfurt', ist_korrekt=False)
    Antwort.objects.create(frage=frage31, text='Dresden', ist_korrekt=True)
    Antwort.objects.create(frage=frage31, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage31, text='Hamburg', ist_korrekt=False)

    frage32 = Frage.objects.create(text='Who is the German author of the famous novel "The Neverending Story"?')
    Antwort.objects.create(frage=frage32, text='Hermann Hesse', ist_korrekt=False)
    Antwort.objects.create(frage=frage32, text='Franz Kafka', ist_korrekt=False)
    Antwort.objects.create(frage=frage32, text='Günter Grass', ist_korrekt=False)
    Antwort.objects.create(frage=frage32, text='Michael Ende', ist_korrekt=True)

    frage33 = Frage.objects.create(text='Which German city is famous for its Neuschwanstein Castle?')
    Antwort.objects.create(frage=frage33, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage33, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage33, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage33, text='Füssen', ist_korrekt=True)

    frage34 = Frage.objects.create(text='Who composed the famous German opera "The Magic Flute"?')
    Antwort.objects.create(frage=frage34, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage34, text='Wolfgang Amadeus Mozart', ist_korrekt=True)
    Antwort.objects.create(frage=frage34, text='Ludwig van Beethoven', ist_korrekt=False)
    Antwort.objects.create(frage=frage34, text='Richard Wagner', ist_korrekt=False)

    frage35 = Frage.objects.create(text='Which German city is known for its Zeppelin Museum?')
    Antwort.objects.create(frage=frage35, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage35, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage35, text='Friedrichshafen', ist_korrekt=True)
    Antwort.objects.create(frage=frage35, text='Cologne', ist_korrekt=False)

    frage36 = Frage.objects.create(text='Who is the German tennis player who has won the most Grand Slam titles?')
    Antwort.objects.create(frage=frage36, text='Boris Becker', ist_korrekt=False)
    Antwort.objects.create(frage=frage36, text='Steffi Graf', ist_korrekt=True)
    Antwort.objects.create(frage=frage36, text='Angelique Kerber', ist_korrekt=False)
    Antwort.objects.create(frage=frage36, text='Alexander Zverev', ist_korrekt=False)

    frage37 = Frage.objects.create(text='Which German city is famous for its Romantic Road, a scenic tourist route?')
    Antwort.objects.create(frage=frage37, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage37, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage37, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage37, text='Rothenburg ob der Tauber', ist_korrekt=True)

    frage38 = Frage.objects.create(text='Who is the German philosopher known for his work on Marxism?')
    Antwort.objects.create(frage=frage38, text='Immanuel Kant', ist_korrekt=False)
    Antwort.objects.create(frage=frage38, text='Friedrich Nietzsche', ist_korrekt=False)
    Antwort.objects.create(frage=frage38, text='Karl Marx', ist_korrekt=True)
    Antwort.objects.create(frage=frage38, text='Arthur Schopenhauer', ist_korrekt=False)

    frage39 = Frage.objects.create(text='Which German city is famous for its St. Nicholas Church?')
    Antwort.objects.create(frage=frage39, text='Frankfurt', ist_korrekt=False)
    Antwort.objects.create(frage=frage39, text='Dresden', ist_korrekt=False)
    Antwort.objects.create(frage=frage39, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage39, text='Leipzig', ist_korrekt=True)

    frage40 = Frage.objects.create(text='Who is the German filmmaker known for his movies "Metropolis" and "M"?')
    Antwort.objects.create(frage=frage40, text='Fritz Lang', ist_korrekt=True)
    Antwort.objects.create(frage=frage40, text='Werner Herzog', ist_korrekt=False)
    Antwort.objects.create(frage=frage40, text='Rainer Werner Fassbinder', ist_korrekt=False)
    Antwort.objects.create(frage=frage40, text='Wim Wenders', ist_korrekt=False)

    frage41 = Frage.objects.create(text='Who won the FIFA World Cup in 2018?')
    Antwort.objects.create(frage=frage41, text='France', ist_korrekt=True)
    Antwort.objects.create(frage=frage41, text='Croatia', ist_korrekt=False)
    Antwort.objects.create(frage=frage41, text='Belgium', ist_korrekt=False)
    Antwort.objects.create(frage=frage41, text='England', ist_korrekt=False)

    frage42 = Frage.objects.create(text='Who is the current President of the United States?')
    Antwort.objects.create(frage=frage42, text='Joe Biden', ist_korrekt=True)
    Antwort.objects.create(frage=frage42, text='Donald Trump', ist_korrekt=False)
    Antwort.objects.create(frage=frage42, text='Barack Obama', ist_korrekt=False)
    Antwort.objects.create(frage=frage42, text='George W. Bush', ist_korrekt=False)

    frage43 = Frage.objects.create(text='Which country is hosting the 2022 Winter Olympics?')
    Antwort.objects.create(frage=frage43, text='China', ist_korrekt=True)
    Antwort.objects.create(frage=frage43, text='Canada', ist_korrekt=False)
    Antwort.objects.create(frage=frage43, text='Russia', ist_korrekt=False)
    Antwort.objects.create(frage=frage43, text='Norway', ist_korrekt=False)

    frage44 = Frage.objects.create(text='Who painted the Mona Lisa?')
    Antwort.objects.create(frage=frage44, text='Leonardo da Vinci', ist_korrekt=True)
    Antwort.objects.create(frage=frage44, text='Pablo Picasso', ist_korrekt=False)
    Antwort.objects.create(frage=frage44, text='Vincent van Gogh', ist_korrekt=False)
    Antwort.objects.create(frage=frage44, text='Michelangelo', ist_korrekt=False)

    frage45 = Frage.objects.create(text='Which city is home to the famous Taj Mahal?')
    Antwort.objects.create(frage=frage45, text='New Delhi', ist_korrekt=False)
    Antwort.objects.create(frage=frage45, text='Agra', ist_korrekt=True)
    Antwort.objects.create(frage=frage45, text='Mumbai', ist_korrekt=False)
    Antwort.objects.create(frage=frage45, text='Jaipur', ist_korrekt=False)

    frage46 = Frage.objects.create(text='Which war lasted from 1939 to 1945?')
    Antwort.objects.create(frage=frage46, text='World War I', ist_korrekt=False)
    Antwort.objects.create(frage=frage46, text='Vietnam War', ist_korrekt=False)
    Antwort.objects.create(frage=frage46, text='Korean War', ist_korrekt=False)
    Antwort.objects.create(frage=frage46, text='World War II', ist_korrekt=True)

    frage47 = Frage.objects.create(text='Who composed the famous symphony "Symphony No. 9" (Choral Symphony)?')
    Antwort.objects.create(frage=frage47, text='Wolfgang Amadeus Mozart', ist_korrekt=False)
    Antwort.objects.create(frage=frage47, text='Ludwig van Beethoven', ist_korrekt=True)
    Antwort.objects.create(frage=frage47, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage47, text='Franz Schubert', ist_korrekt=False)

    frage48 = Frage.objects.create(text='Who is the current President of Germany?')
    Antwort.objects.create(frage=frage48, text='Frank-Walter Steinmeier', ist_korrekt=True)
    Antwort.objects.create(frage=frage48, text='Angela Merkel', ist_korrekt=False)
    Antwort.objects.create(frage=frage48, text='Olaf Scholz', ist_korrekt=False)
    Antwort.objects.create(frage=frage48, text='Annalena Baerbock', ist_korrekt=False)

    frage49 = Frage.objects.create(text='Which German football club has won the most Bundesliga titles?')
    Antwort.objects.create(frage=frage49, text='Bayern Munich', ist_korrekt=True)
    Antwort.objects.create(frage=frage49, text='Borussia Dortmund', ist_korrekt=False)
    Antwort.objects.create(frage=frage49, text='Borussia Mönchengladbach', ist_korrekt=False)
    Antwort.objects.create(frage=frage49, text='Hamburger SV', ist_korrekt=False)

    frage50 = Frage.objects.create(text='Which German city hosted the Summer Olympics in 1936?')
    Antwort.objects.create(frage=frage50, text='Berlin', ist_korrekt=True)
    Antwort.objects.create(frage=frage50, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage50, text='Hamburg', ist_korrekt=False)
    Antwort.objects.create(frage=frage50, text='Frankfurt', ist_korrekt=False)

    frage51 = Frage.objects.create(text='Which German city is home to the famous Neuschwanstein Castle?')
    Antwort.objects.create(frage=frage51, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage51, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage51, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage51, text='Füssen', ist_korrekt=True)

    frage52 = Frage.objects.create(text='Which German painter is known for his famous artwork "The Persistence of Memory"?')
    Antwort.objects.create(frage=frage52, text='Caspar David Friedrich', ist_korrekt=False)
    Antwort.objects.create(frage=frage52, text='Albrecht Dürer', ist_korrekt=False)
    Antwort.objects.create(frage=frage52, text='Max Ernst', ist_korrekt=False)
    Antwort.objects.create(frage=frage52, text='Salvador Dalí', ist_korrekt=True)

    frage53 = Frage.objects.create(text='When did Germany reunify and the Berlin Wall fall?')
    Antwort.objects.create(frage=frage53, text='1989', ist_korrekt=True)
    Antwort.objects.create(frage=frage53, text='1990', ist_korrekt=False)
    Antwort.objects.create(frage=frage53, text='1991', ist_korrekt=False)
    Antwort.objects.create(frage=frage53, text='1992', ist_korrekt=False)

    frage54 = Frage.objects.create(text='How old are the Germans in average?')
    Antwort.objects.create(frage=frage54, text='44.5', ist_korrekt=True)
    Antwort.objects.create(frage=frage54, text='34.2', ist_korrekt=False)
    Antwort.objects.create(frage=frage54, text='40.7', ist_korrekt=False)
    Antwort.objects.create(frage=frage54, text='29.9', ist_korrekt=False)

    frage55 = Frage.objects.create(text='Which German city hosted the 1972 Olympic Games?')
    Antwort.objects.create(frage=frage55, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage55, text='Hamburg', ist_korrekt=False)
    Antwort.objects.create(frage=frage55, text='Munich', ist_korrekt=True)
    Antwort.objects.create(frage=frage55, text='Cologne', ist_korrekt=False)

    frage56 = Frage.objects.create(text='Which river forms part of the border between Germany and Poland?')
    Antwort.objects.create(frage=frage56, text='Oder ', ist_korrekt=True)
    Antwort.objects.create(frage=frage56, text='Main', ist_korrekt=False)
    Antwort.objects.create(frage=frage56, text='Weser', ist_korrekt=False)
    Antwort.objects.create(frage=frage56, text='Saale', ist_korrekt=False)

    frage57 = Frage.objects.create(text='Which German painter is known for his expressionist works?')
    Antwort.objects.create(frage=frage57, text='Albrecht Dürer', ist_korrekt=False)
    Antwort.objects.create(frage=frage57, text='Caspar David Friedrich', ist_korrekt=False)
    Antwort.objects.create(frage=frage57, text='Franz Marc', ist_korrekt=True)
    Antwort.objects.create(frage=frage57, text='Gerhard Richter', ist_korrekt=False)

    frage58 = Frage.objects.create(text='Which German band is known for their hit song "99 Luftballons"?')
    Antwort.objects.create(frage=frage58, text='Rammstein', ist_korrekt=False)
    Antwort.objects.create(frage=frage58, text='Kraftwerk', ist_korrekt=False)
    Antwort.objects.create(frage=frage58, text='Scorpions', ist_korrekt=False)
    Antwort.objects.create(frage=frage58, text='Nena', ist_korrekt=True)

    frage59 = Frage.objects.create(text='In which year did the German reunification take place?')
    Antwort.objects.create(frage=frage59, text='1989', ist_korrekt=False)
    Antwort.objects.create(frage=frage59, text='1990', ist_korrekt=True)
    Antwort.objects.create(frage=frage59, text='1991', ist_korrekt=False)
    Antwort.objects.create(frage=frage59, text='1992', ist_korrekt=False)

    frage60 = Frage.objects.create(text='Which German city is famous for its Museum Island, home to several world-renowned museums?')
    Antwort.objects.create(frage=frage60, text='Frankfurt', ist_korrekt=False)
    Antwort.objects.create(frage=frage60, text='Dresden', ist_korrekt=False)
    Antwort.objects.create(frage=frage60, text='Berlin', ist_korrekt=True)
    Antwort.objects.create(frage=frage60, text='Cologne', ist_korrekt=False)

    frage61 = Frage.objects.create(text='Which German city is home to the Reichstag building, the seat of the German Parliament?')
    Antwort.objects.create(frage=frage61, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage61, text='Berlin', ist_korrekt=True)
    Antwort.objects.create(frage=frage61, text='Cologne', ist_korrekt=False)
    Antwort.objects.create(frage=frage61, text='Hamburg', ist_korrekt=False)

    frage62 = Frage.objects.create(text='Who composed the famous German opera "The Magic Flute"?')
    Antwort.objects.create(frage=frage62, text='Richard Wagner', ist_korrekt=False)
    Antwort.objects.create(frage=frage62, text='Wolfgang Amadeus Mozart', ist_korrekt=True)
    Antwort.objects.create(frage=frage62, text='Ludwig van Beethoven', ist_korrekt=False)
    Antwort.objects.create(frage=frage62, text='Johann Sebastian Bach', ist_korrekt=False)

    frage63 = Frage.objects.create(text='Which German city is famous for its Christmas market and the Nuremberg sausages?')
    Antwort.objects.create(frage=frage63, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage63, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage63, text='Nuremberg', ist_korrekt=True)
    Antwort.objects.create(frage=frage63, text='Cologne', ist_korrekt=False)

    frage64 = Frage.objects.create(text='Who is the German author of the novel "Steppenwolf" and the play "Faust"?')
    Antwort.objects.create(frage=frage64, text='Johann Wolfgang von Goethe', ist_korrekt=False)
    Antwort.objects.create(frage=frage64, text='Thomas Mann', ist_korrekt=True)
    Antwort.objects.create(frage=frage64, text='Franz Kafka', ist_korrekt=False)
    Antwort.objects.create(frage=frage64, text='Heinrich Heine', ist_korrekt=False)

    frage65 = Frage.objects.create(text='Who wrote the German fairy tale "Hansel and Gretel"?')
    Antwort.objects.create(frage=frage65, text='Jacob Grimm', ist_korrekt=False)
    Antwort.objects.create(frage=frage65, text='Wilhelm Grimm', ist_korrekt=False)
    Antwort.objects.create(frage=frage65, text='Hans Christian Andersen', ist_korrekt=False)
    Antwort.objects.create(frage=frage65, text='The Brothers Grimm', ist_korrekt=True)

    frage66 = Frage.objects.create(text='Which German city is famous for its opera house, the Semperoper?')
    Antwort.objects.create(frage=frage66, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage66, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage66, text='Dresden', ist_korrekt=True)
    Antwort.objects.create(frage=frage66, text='Cologne', ist_korrekt=False)

    frage67 = Frage.objects.create(text='Who is the German composer of the famous "Ride of the Valkyries" from the opera "Die Walküre"?')
    Antwort.objects.create(frage=frage67, text='Johann Sebastian Bach', ist_korrekt=False)
    Antwort.objects.create(frage=frage67, text='Wolfgang Amadeus Mozart', ist_korrekt=False)
    Antwort.objects.create(frage=frage67, text='Ludwig van Beethoven', ist_korrekt=False)
    Antwort.objects.create(frage=frage67, text='Richard Wagner', ist_korrekt=True)

    frage68 = Frage.objects.create(text='Which German city is known for its international trade fair, the Messe Frankfurt?')
    Antwort.objects.create(frage=frage68, text='Munich', ist_korrekt=False)
    Antwort.objects.create(frage=frage68, text='Berlin', ist_korrekt=False)
    Antwort.objects.create(frage=frage68, text='Frankfurt', ist_korrekt=True)
    Antwort.objects.create(frage=frage68, text='Hamburg', ist_korrekt=False)

    frage69 = Frage.objects.create(text='What is the value of the definite integral ∫(0 to π/2) sin(x) dx?')
    Antwort.objects.create(frage=frage69, text='1', ist_korrekt=False)
    Antwort.objects.create(frage=frage69, text='0', ist_korrekt=False)
    Antwort.objects.create(frage=frage69, text='π/2', ist_korrekt=True)
    Antwort.objects.create(frage=frage69, text='π', ist_korrekt=False)

    frage70 = Frage.objects.create(text='Which of the following is the solution to the equation 2x^2 + 3x - 2 = 0?')
    Antwort.objects.create(frage=frage70, text='-2', ist_korrekt=False)
    Antwort.objects.create(frage=frage70, text='1/2', ist_korrekt=True)
    Antwort.objects.create(frage=frage70, text='-1/2', ist_korrekt=False)
    Antwort.objects.create(frage=frage70, text='2', ist_korrekt=False)

    frage71 = Frage.objects.create(text='What is the value of log(base 2) 16?')
    Antwort.objects.create(frage=frage71, text='2', ist_korrekt=False)
    Antwort.objects.create(frage=frage71, text='4', ist_korrekt=True)
    Antwort.objects.create(frage=frage71, text='8', ist_korrekt=False)
    Antwort.objects.create(frage=frage71, text='16', ist_korrekt=False)

    frage72 = Frage.objects.create(text='What is the value of the determinant of the matrix A = [3 1; -2 4]?')
    Antwort.objects.create(frage=frage72, text='7', ist_korrekt=True)
    Antwort.objects.create(frage=frage72, text='10', ist_korrekt=False)
    Antwort.objects.create(frage=frage72, text='11', ist_korrekt=False)
    Antwort.objects.create(frage=frage72, text='14', ist_korrekt=False)

    frage73 = Frage.objects.create(text='Whats the name of the biggest lake of germany?')
    Antwort.objects.create(frage=frage73, text='Lake of Spöck', ist_korrekt=False)
    Antwort.objects.create(frage=frage73, text='Lake of germany', ist_korrekt=False)
    Antwort.objects.create(frage=frage73, text='Lake of Konstanz', ist_korrekt=True)
    Antwort.objects.create(frage=frage73, text='Lake of Berlin', ist_korrekt=False)

    frage74 = Frage.objects.create(text='Which countries are connected trough the lake of Konstanz?')
    Antwort.objects.create(frage=frage74, text='Spain, Italy, Switzerland', ist_korrekt=False)
    Antwort.objects.create(frage=frage74, text='Germany, Switzerland, Austria', ist_korrekt=True)
    Antwort.objects.create(frage=frage74, text='Netherlands, Germany, Belgium', ist_korrekt=False)
    Antwort.objects.create(frage=frage74, text='Germany, Italy, Hungary', ist_korrekt=False)

    frage75 = Frage.objects.create(text='Which of the buttons is furthest down?')
    Antwort.objects.create(frage=frage75, text='Button1', ist_korrekt=False)
    Antwort.objects.create(frage=frage75, text='Button2', ist_korrekt=False)
    Antwort.objects.create(frage=frage75, text='Button3', ist_korrekt=False)
    Antwort.objects.create(frage=frage75, text='Button4', ist_korrekt=True)

    frage76 = Frage.objects.create(text='Who is Günther Jauch')
    Antwort.objects.create(frage=frage76, text='FC Bayern soccer player', ist_korrekt=False)
    Antwort.objects.create(frage=frage76, text='Communist politician ', ist_korrekt=False)
    Antwort.objects.create(frage=frage76, text='Host of Who Wants To Be A Millionaire', ist_korrekt=True)
    Antwort.objects.create(frage=frage76, text='Mayor of Spöck', ist_korrekt=False)

    frage77 = Frage.objects.create(text='What is the small town of Blaubeuren in Germany known for')
    Antwort.objects.create(frage=frage77, text='oldest church', ist_korrekt=False)
    Antwort.objects.create(frage=frage77, text='oldest newborn', ist_korrekt=False)
    Antwort.objects.create(frage=frage77, text='oldest old town', ist_korrekt=False)
    Antwort.objects.create(frage=frage77, text='oldest musical instrument', ist_korrekt=True)

    frage78 = Frage.objects.create(text='What is the sound of one hand clapping?')
    Antwort.objects.create(frage=frage78, text='Thud', ist_korrekt=False)
    Antwort.objects.create(frage=frage78, text='Whoosh', ist_korrekt=False)
    Antwort.objects.create(frage=frage78, text='Silence', ist_korrekt=True)
    Antwort.objects.create(frage=frage78, text='Snap', ist_korrekt=False)

    frage79 = Frage.objects.create(text='If there are three apples and you take away two, how many apples do you have?')
    Antwort.objects.create(frage=frage79, text='Two ', ist_korrekt=True)
    Antwort.objects.create(frage=frage79, text='One', ist_korrekt=False)
    Antwort.objects.create(frage=frage79, text='None', ist_korrekt=False)
    Antwort.objects.create(frage=frage79, text='Three', ist_korrekt=False)

    frage80 = Frage.objects.create(text='How long does it take the earth to turn around itself once?')
    Antwort.objects.create(frage=frage80, text='24 hours', ist_korrekt=False)
    Antwort.objects.create(frage=frage80, text='23 hours, 56 minutes', ist_korrekt=True)
    Antwort.objects.create(frage=frage80, text='7 days', ist_korrekt=False)
    Antwort.objects.create(frage=frage80, text='31 days', ist_korrekt=False)

    frage81 = Frage.objects.create(text='How many months have 28 days?')
    Antwort.objects.create(frage=frage81, text='Only February', ist_korrekt=False)
    Antwort.objects.create(frage=frage81, text='Three months', ist_korrekt=False)
    Antwort.objects.create(frage=frage81, text='Six months', ist_korrekt=False)
    Antwort.objects.create(frage=frage81, text=' All months', ist_korrekt=True)

    frage82 = Frage.objects.create(text='If a plane crashes on the border of the United States and Canada, where do they bury the survivors?')
    Antwort.objects.create(frage=frage82, text='United States', ist_korrekt=False)
    Antwort.objects.create(frage=frage82, text='Canada', ist_korrekt=False)
    Antwort.objects.create(frage=frage82, text='Nowhere, survivors arent buried', ist_korrekt=True)
    Antwort.objects.create(frage=frage82, text='It depends on the survivors nationality', ist_korrekt=False)

    frage83 = Frage.objects.create(text='What is the answer to life, the universe, and everything?')
    Antwort.objects.create(frage=frage83, text='42 ', ist_korrekt=True)
    Antwort.objects.create(frage=frage83, text='Love', ist_korrekt=False)
    Antwort.objects.create(frage=frage83, text='Happiness', ist_korrekt=False)
    Antwort.objects.create(frage=frage83, text='Its subjective', ist_korrekt=False)

    frage84 = Frage.objects.create(text='Which event marked the end of the division between East and West Germany?')
    Antwort.objects.create(frage=frage84, text='Berlin Wall construction', ist_korrekt=False)
    Antwort.objects.create(frage=frage84, text='Berlin Wall demolition', ist_korrekt=True)
    Antwort.objects.create(frage=frage84, text='German Reunification Day', ist_korrekt=False)
    Antwort.objects.create(frage=frage84, text='Treaty of Versailles', ist_korrekt=False)

    frage85 = Frage.objects.create(text='Who was the leader of East Germany during the construction of the Berlin Wall?')
    Antwort.objects.create(frage=frage85, text='Angela Merkel', ist_korrekt=False)
    Antwort.objects.create(frage=frage85, text='Walter Ulbricht', ist_korrekt=False)
    Antwort.objects.create(frage=frage85, text='Konrad Adenauer', ist_korrekt=False)
    Antwort.objects.create(frage=frage85, text='Erich Honecker', ist_korrekt=True)

    frage86 = Frage.objects.create(text='What was the name of the German resistance group against Adolf Hitler?')
    Antwort.objects.create(frage=frage86, text='Black Eagle', ist_korrekt=False)
    Antwort.objects.create(frage=frage86, text='Red Army Faction', ist_korrekt=False)
    Antwort.objects.create(frage=frage86, text='White Rose', ist_korrekt=True)
    Antwort.objects.create(frage=frage86, text='Iron Cross', ist_korrekt=False)

    frage87 = Frage.objects.create(text='Who was the first female Chancellor of Germany?')
    Antwort.objects.create(frage=frage87, text='Angela Merkel', ist_korrekt=True)
    Antwort.objects.create(frage=frage87, text='Helmut Kohl', ist_korrekt=False)
    Antwort.objects.create(frage=frage87, text='Gerhard Schröder', ist_korrekt=False)
    Antwort.objects.create(frage=frage87, text='Konrad Adenauer', ist_korrekt=False)

    frage88 = Frage.objects.create(text='Which event led to the outbreak of World War I?')
    Antwort.objects.create(frage=frage88, text='Invasion of Poland', ist_korrekt=False)
    Antwort.objects.create(frage=frage88, text='Assassination of Archduke Franz Ferdinand', ist_korrekt=True)
    Antwort.objects.create(frage=frage88, text='Treaty of Versailles', ist_korrekt=False)
    Antwort.objects.create(frage=frage88, text='German Reunification', ist_korrekt=False)

    frage89 = Frage.objects.create(text='When was the Weimar Republic established in Germany?')
    Antwort.objects.create(frage=frage89, text='1914', ist_korrekt=False)
    Antwort.objects.create(frage=frage89, text='1933', ist_korrekt=False)
    Antwort.objects.create(frage=frage89, text='1923', ist_korrekt=False)
    Antwort.objects.create(frage=frage89, text='1918 ', ist_korrekt=True)

    frage90 = Frage.objects.create(text='Who led the German reunification process in 1990?')
    Antwort.objects.create(frage=frage90, text='Konrad Adenauer', ist_korrekt=False)
    Antwort.objects.create(frage=frage90, text='Angela Merkel', ist_korrekt=False)
    Antwort.objects.create(frage=frage90, text='Helmut Kohl', ist_korrekt=True)
    Antwort.objects.create(frage=frage90, text='Willy Brandt', ist_korrekt=False)

    frage91 = Frage.objects.create(text='When did the Nazi Party come to power in Germany?')
    Antwort.objects.create(frage=frage91, text='1933', ist_korrekt=True)
    Antwort.objects.create(frage=frage91, text='1945', ist_korrekt=False)
    Antwort.objects.create(frage=frage91, text='1949', ist_korrekt=False)
    Antwort.objects.create(frage=frage91, text='1957', ist_korrekt=False)

    frage92 = Frage.objects.create(text='What is the largest island in Germany?')
    Antwort.objects.create(frage=frage92, text='Usedom', ist_korrekt=False)
    Antwort.objects.create(frage=frage92, text='Rügen ', ist_korrekt=True)
    Antwort.objects.create(frage=frage92, text='Sylt', ist_korrekt=False)
    Antwort.objects.create(frage=frage92, text='Fehmarn', ist_korrekt=False)

    frage93 = Frage.objects.create(text='Which German state is home to the Black Forest?')
    Antwort.objects.create(frage=frage93, text='Bavaria', ist_korrekt=False)
    Antwort.objects.create(frage=frage93, text='Hesse', ist_korrekt=False)
    Antwort.objects.create(frage=frage93, text='Saxony', ist_korrekt=False)
    Antwort.objects.create(frage=frage93, text='Baden-Württemberg', ist_korrekt=True)

    frage94 = Frage.objects.create(text='Which river forms part of the border between Germany and Switzerland?')
    Antwort.objects.create(frage=frage94, text='Elbe', ist_korrekt=False)
    Antwort.objects.create(frage=frage94, text='Danube', ist_korrekt=False)
    Antwort.objects.create(frage=frage94, text='Rhine ', ist_korrekt=True)
    Antwort.objects.create(frage=frage94, text='Main', ist_korrekt=False)

    frage95 = Frage.objects.create(text='Where is the largest port in Germany?')
    Antwort.objects.create(frage=frage95, text='Hamburg ', ist_korrekt=True)
    Antwort.objects.create(frage=frage95, text='Kiel', ist_korrekt=False)
    Antwort.objects.create(frage=frage95, text='Bremen', ist_korrekt=False)
    Antwort.objects.create(frage=frage95, text='Rostock', ist_korrekt=False)

    frage96 = Frage.objects.create(text='What produces the brand Steiff')
    Antwort.objects.create(frage=frage96, text='cars', ist_korrekt=False)
    Antwort.objects.create(frage=frage96, text='Teddy bears', ist_korrekt=True)
    Antwort.objects.create(frage=frage96, text='books', ist_korrekt=False)
    Antwort.objects.create(frage=frage96, text='clocks', ist_korrekt=False)

    frage97 = Frage.objects.create(text='What produces the brand Märklin')
    Antwort.objects.create(frage=frage97, text='cars', ist_korrekt=False)
    Antwort.objects.create(frage=frage97, text='Model railroad', ist_korrekt=True)
    Antwort.objects.create(frage=frage97, text='books', ist_korrekt=False)
    Antwort.objects.create(frage=frage97, text='teddy bears', ist_korrekt=False)

    frage98 = Frage.objects.create(text='What is a euphonium')
    Antwort.objects.create(frage=frage98, text='A Card Game', ist_korrekt=False)
    Antwort.objects.create(frage=frage98, text='Something to Drink', ist_korrekt=False)
    Antwort.objects.create(frage=frage98, text='A Part of the Ear', ist_korrekt=False)
    Antwort.objects.create(frage=frage98, text='Music Instrument', ist_korrekt=True)

    frage99 = Frage.objects.create(text='What is the chemical symbol for the element gold?')
    Antwort.objects.create(frage=frage99, text='Go', ist_korrekt=False)
    Antwort.objects.create(frage=frage99, text='Ag', ist_korrekt=False)
    Antwort.objects.create(frage=frage99, text='Au ', ist_korrekt=True)
    Antwort.objects.create(frage=frage99, text='Pt', ist_korrekt=False)

    frage100 = Frage.objects.create(text='What is the largest ocean on Earth?')
    Antwort.objects.create(frage=frage100, text='Pacific Ocean', ist_korrekt=True)
    Antwort.objects.create(frage=frage100, text='Atlantic Ocean', ist_korrekt=False)
    Antwort.objects.create(frage=frage100, text='Indian Ocean', ist_korrekt=False)
    Antwort.objects.create(frage=frage100, text='Arctic Ocean', ist_korrekt=False)

    frage101 = Frage.objects.create(text='What is the largest organ in the human body?')
    Antwort.objects.create(frage=frage101, text='Brain', ist_korrekt=False)
    Antwort.objects.create(frage=frage101, text='Skin ', ist_korrekt=True)
    Antwort.objects.create(frage=frage101, text='Liver', ist_korrekt=False)
    Antwort.objects.create(frage=frage101, text='Heart', ist_korrekt=False)

    frage102 = Frage.objects.create(text='Which planet is closest to the Sun?')
    Antwort.objects.create(frage=frage102, text='Mercury', ist_korrekt=True)
    Antwort.objects.create(frage=frage102, text='Venus', ist_korrekt=False)
    Antwort.objects.create(frage=frage102, text='Saturn', ist_korrekt=False)
    Antwort.objects.create(frage=frage102, text='Mars', ist_korrekt=False)

    frage103 = Frage.objects.create(text='Who wrote the play Romeo and Juliet?')
    Antwort.objects.create(frage=frage103, text='Jane Austen', ist_korrekt=False)
    Antwort.objects.create(frage=frage103, text='Charles Dickens', ist_korrekt=False)
    Antwort.objects.create(frage=frage103, text='Mark Twain', ist_korrekt=False)
    Antwort.objects.create(frage=frage103, text='William Shakespeare', ist_korrekt=True)

    frage104 = Frage.objects.create(text='Who invented the telephone?')
    Antwort.objects.create(frage=frage104, text='Thomas Edison', ist_korrekt=False)
    Antwort.objects.create(frage=frage104, text='Alexander Graham Bell', ist_korrekt=True)
    Antwort.objects.create(frage=frage104, text='Albert Einstein', ist_korrekt=False)
    Antwort.objects.create(frage=frage104, text='Isaac Newton', ist_korrekt=False)

    frage105 = Frage.objects.create(text='What is the smallest country in the world by land area?')
    Antwort.objects.create(frage=frage105, text='Vatican City', ist_korrekt=True)
    Antwort.objects.create(frage=frage105, text='Monaco', ist_korrekt=False)
    Antwort.objects.create(frage=frage105, text='Liechtenstein', ist_korrekt=False)
    Antwort.objects.create(frage=frage105, text='San Marino', ist_korrekt=False)

    frage106 = Frage.objects.create(text='What is the largest species of penguin?')
    Antwort.objects.create(frage=frage106, text='Emperor Penguin', ist_korrekt=True)
    Antwort.objects.create(frage=frage106, text='Adelie Penguin', ist_korrekt=False)
    Antwort.objects.create(frage=frage106, text='King Penguin', ist_korrekt=False)
    Antwort.objects.create(frage=frage106, text='Gentoo Penguin', ist_korrekt=False)

    frage107 = Frage.objects.create(text='Which German political party was involved in the controversial "Waldheimer Affair" in the 1980s?')
    Antwort.objects.create(frage=frage107, text='The Greens (Die Grünen)', ist_korrekt=False)
    Antwort.objects.create(frage=frage107, text='Free Democratic Party (FDP)', ist_korrekt=False)
    Antwort.objects.create(frage=frage107, text='Social Democratic Party (SPD)', ist_korrekt=False)
    Antwort.objects.create(frage=frage107, text='Christian Democratic Union (CDU)', ist_korrekt=True)

    frage108 = Frage.objects.create(text='Which German political party advocates for a basic income for all citizens?')
    Antwort.objects.create(frage=frage108, text='Free Democratic Party (FDP)', ist_korrekt=False)
    Antwort.objects.create(frage=frage108, text='The Left (Die Linke)', ist_korrekt=True)
    Antwort.objects.create(frage=frage108, text='Alternative for Germany (AfD)', ist_korrekt=False)
    Antwort.objects.create(frage=frage108, text='Pirate Party Germany (Piraten)', ist_korrekt=False)

    frage109 = Frage.objects.create(text='Which political party advocates for the withdrawal of Germany from the European Union?')
    Antwort.objects.create(frage=frage109, text='Alternative for Germany (AfD)', ist_korrekt=True)
    Antwort.objects.create(frage=frage109, text='Free Democratic Party (FDP)', ist_korrekt=False)
    Antwort.objects.create(frage=frage109, text='The Greens (Die Grünen)', ist_korrekt=False)
    Antwort.objects.create(frage=frage109, text='Social Democratic Party (SPD)', ist_korrekt=False)

    frage110 = Frage.objects.create(text='Which German political party was associated with the student movement of the 1960s and 1970s?')
    Antwort.objects.create(frage=frage110, text='Christian Democratic Union (CDU)', ist_korrekt=False)
    Antwort.objects.create(frage=frage110, text='Social Democratic Party (SPD)', ist_korrekt=False)
    Antwort.objects.create(frage=frage110, text='Free Democratic Party (FDP)', ist_korrekt=False)
    Antwort.objects.create(frage=frage110, text='The Greens (Die Grünen)', ist_korrekt=True)

    frage111 = Frage.objects.create(text='Who was the first Chancellor of the reunified Germany?')
    Antwort.objects.create(frage=frage111, text='Gerhard Schröder', ist_korrekt=False)
    Antwort.objects.create(frage=frage111, text='Helmut Kohl', ist_korrekt=True)
    Antwort.objects.create(frage=frage111, text='Helmut Schmidt', ist_korrekt=False)
    Antwort.objects.create(frage=frage111, text='Sanf Essig', ist_korrekt=False)

    frage112 = Frage.objects.create(text='Who was the first President of the Federal Republic of Germany?')
    Antwort.objects.create(frage=frage112, text='Theodor Heuss', ist_korrekt=True)
    Antwort.objects.create(frage=frage112, text='Gustav Heinemann', ist_korrekt=False)
    Antwort.objects.create(frage=frage112, text='Walter Scheel', ist_korrekt=False)
    Antwort.objects.create(frage=frage112, text='Kuhn', ist_korrekt=False)

    userfrage = Frage.objects.create(text='Where is the church with the worlds highest church tower?')
    Antwort.objects.create(frage=userfrage, text='Ulm', ist_korrekt=True)
    Antwort.objects.create(frage=userfrage, text='Köln', ist_korrekt=False)
    Antwort.objects.create(frage=userfrage, text='Bamberg', ist_korrekt=False)
    Antwort.objects.create(frage=userfrage, text='Hamburg', ist_korrekt=False)

    print("Daten erfolgreich eingefügt.")

if __name__ == '__main__':
    daten_einfuegen()